name: Deploy

on:
  push:
    branches: [ main ]
    tags:
      - "*"
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android Sample
        run: flutter build apk -t lib/main.dart

      - name: Build iOS Sample
        run: flutter build ios lib/main.dart --release

      - name: Publishing
        run: flutter pub publish --dry-run
