name: Release

on:
  push:
    tags:
      - '*' # Push events to matching *, i.e. 1.0, 20.15.10
  workflow_dispatch:

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Android SDK version as ENV
        run: |
          echo "android_sdk_version=$(sh .github/scripts/extract_android_sdk_version.sh)" >> $GITHUB_ENV

      - name: Print Android SDK Version
        run: |
          echo "Android SDK version is: ${{ env.android_sdk_version }}"

      - name: Set iOS SDK version as ENV
        run: |
          echo "ios_sdk_version=$(sh .github/scripts/extract_ios_sdk_version.sh)" >> $GITHUB_ENV

      - name: Print iOS SDK Version
        run: |
          echo "iOS SDK version is: ${{ env.ios_sdk_version }}"

      - name: Create Release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.CUSTOM_GITHUB_TOKEN }} # Use custom token to trigger following workflows
          script: |
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ${{ github.ref }},
              tag_name: ${{ github.ref }},
              draft: true,
              prerelease: false,
              body: |
                - Update latest versions of native Android (${{ env.android_sdk_version }}) and iOS (${{ env.ios_sdk_version }}) sdks
            
                More info: https://developers.didomi.io/cmp/mobile-sdk
            });
