name: Test Android & iOS

# Trigger the workflow manually or after push a commit
on: [ push, workflow_dispatch ]

jobs:
#  analyse:
#    name: Analyse Flutter
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin'
#          java-version: '17'
#      - uses: subosito/flutter-action@v2
#        with:
#          channel: "stable"
#
#      - name: Install dependencies
#        run: flutter pub get
#
#      # Uncomment this step to verify the use of 'dart format' on each commit.
#      # - name: Verify formatting
#      #   run: dart format --output=none --set-exit-if-changed .
#      #   run: dart format --output=none --set-exit-if-changed example
#
#      # Consider passing '--fatal-infos' for slightly stricter analysis.
#      - name: Analyze project source
#        run: flutter analyze --no-fatal-infos

  # job responsible for running Flutter tests on iOS devices
  ios:
    name: Testing iOS
#    needs: analyse
    runs-on: macos-latest
#    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
#          architecture: arm64 # optional value for v2 (use self-hosted mac mini)

      - name: Install dependencies
        run: flutter pub get

      - name: Run pod update
        working-directory: ./example/ios
        run: pod update

      - name: List all simulators
        run: "xcrun xctrace list devices"

      - name: Build & run all tests
        run: sh .github/scripts/uitests_for_ios.sh

      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: example/machine.log

  # job responsible for running Flutter tests on Android devices
  android:
    name: Testing Android
#    needs: analyse
    runs-on: macos-latest
#    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
#          architecture: arm64 # optional value for v2 (use self-hosted mac mini)

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run integration tests
        # more info on https://github.com/ReactiveCircus/android-emulator-runner
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew bulk
          working-directory: ./example/android
