name: Test

# Triggered on pull request or manually
on:
  push:
    branches:
      - "939-*"
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyse:
    name: Analyse Flutter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .
      #   run: dart format --output=none --set-exit-if-changed example

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: flutter analyze

  test_android:
    name: Testing Android
    needs: analyse
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      # Connect to GCloud
      - name: Login to Google Cloud
        uses: google-github-actions/setup-gcloud@master
        with:
          version: "342.0.0"
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      - name: Set current project
        run: gcloud config set project ${{ secrets.FIREBASE_PROJECT_ID }}

      # Build and upload each scenarios to firebase
      - name: Run UI tests
        run: sh .github/scripts/uitests_for_android.sh

  test_ios:
    name: Testing iOS
    needs: analyse
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      # Add Code sign certificate for iOS build
      - name: Add sign certificate for iOS build
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

      # Add Provisioning profile for iOS build
      - name: Import provisioning profile for iOS build
        env:
          PROVISIONING_PROFILE_DATA: ${{ secrets.PROVISIONING_PROFILE_DATA }}
        run: sh .github/scripts/import_profile.sh

      # Connect to GCloud
      - name: Login to Google Cloud
        uses: google-github-actions/setup-gcloud@master
        with:
          version: "342.0.0"
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      - name: Set current project
        run: gcloud config set project ${{ secrets.FIREBASE_PROJECT_ID }}

      # Build and upload each scenarios to firebase
      - name: Run UI tests
        run: sh .github/scripts/uitests_for_ios.sh
