name: Test Android & iOS

# Trigger the workflow manually or after push a commit
on: [ push, workflow_dispatch ]

jobs:
  # job responsible for running Flutter tests on iOS devices
  ios:
    name: Testing iOS
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: arm64 # optional value for v2 (use self-hosted mac mini)

      - name: Install dependencies
        run: flutter pub get

      - name: Run pod update
        working-directory: ./example/ios
        run: pod update

      - name: List all simulators
        run: "xcrun xctrace list devices"

      - name: Build & run all tests
        run: sh .github/scripts/uitests_for_ios.sh

      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: example/machine.log

  # job responsible for running Flutter tests on Android devices
  android:
    name: Testing Android
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: arm64 # optional value for v2 (use self-hosted mac mini)

      - name: Install dependencies
        run: flutter pub get

      - name: Build & run all tests
        run: sh .github/scripts/uitests_for_android.sh

      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: example/machine.log
