name: Update

# Triggered manually or on release creation
on:
  workflow_dispatch:
    inputs:
      increment:
        description: "Increment (major, minor, patch)"
        required: true
        default: "patch"
      force:
        description: "Force update (even if sdk is up to date)"
        required: false
        default: "false"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    name: Update version and dependencies
    runs-on: macos-latest # required for pod info / update

    steps:
      - name: Checkout
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Check if Flutter SDK requires update
        if: github.event.inputs.force != 'true'
        run: bash .github/scripts/check_before_update.sh

      - name: Update Flutter SDK
        run: bash .github/scripts/update.sh ${{ github.event.inputs.increment }}

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          author_email: "nicolas.chaix@didomi.io"
          author_name: "Nicolas CHAIX"
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "Update Dependencies and increment ${{ github.event.inputs.increment }} version"

      - name: Trigger Tag
        run: |
          curl --request POST \
              --url 'https://api.github.com/repos/didomi/flutter/actions/workflows/tag.yml/dispatches' \
              --header 'authorization: Bearer ${{ secrets.CUSTOM_GITHUB_TOKEN }}' \
              --data '{ "ref": "${{ github.ref }}" }'
